# Generated by Django 5.2.13 on 2026-04-14 00:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('FINISHED', 'Finished'), ('FAILED', 'Failed')], default='RUNNING', max_length=20)),
                ('step', models.CharField(choices=[('DATA_RECOLLECTION', 'Data Recollection'), ('STORING_RAW_DATA', 'Storing Raw Data'), ('CLEANING_RAW_DATA', 'Cleaning Raw Data'), ('STORING_CLEANED_DATA', 'Storing Cleaned Data')], max_length=50)),
                ('last_log', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='core.client')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='core.pipeline')),
            ],
        ),
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='raw_data', to='core.run')),
            ],
        ),
        migrations.CreateModel(
            name='CleanedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cleaned_data', to='core.run')),
            ],
        ),
    ]
