# Generated by Django 5.2.13 on 2026-05-03 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='pipelines',
            field=models.ManyToManyField(blank=True, related_name='clients', to='core.pipeline'),
        ),
    ]
