# Generated by Django 5.2.13 on 2026-05-04 04:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_client_pipelines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='pipelines',
        ),
        migrations.CreateModel(
            name='PipelineInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pipeline_params', models.JSONField(blank=True, default=dict)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_instances', to='core.client')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='core.pipeline')),
            ],
        ),
    ]
