# Generated by Django 5.2.13 on 2026-05-07 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_client_pipelines_pipelineinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_concurrent_instances', models.IntegerField(default=2)),
                ('window_start_hour', models.IntegerField(default=9)),
                ('window_end_hour', models.IntegerField(default=18)),
            ],
        ),
        migrations.RemoveField(
            model_name='pipelineinstance',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pipelineinstance',
            name='label',
        ),
        migrations.AddField(
            model_name='pipelineinstance',
            name='alias',
            field=models.CharField(blank=True, help_text='Custom name for this instance', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pipelineinstance',
            name='frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('MANUAL', 'Manual')], default='MANUAL', max_length=10),
        ),
        migrations.AddField(
            model_name='pipelineinstance',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pipelineinstance',
            name='is_queued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pipelineinstance',
            name='last_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='instance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='core.pipelineinstance'),
            preserve_default=False,
        ),
    ]
