# Generated by Django 5.2.14 on 2026-05-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_scrapersettings_remove_pipelineinstance_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='attempt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='run',
            name='run_data',
            field=models.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('QUEQUE', 'Queque'), ('RUNNING', 'Running'), ('FINISHED', 'Finished'), ('PAUSED', 'Paused'), ('FAILED', 'Failed')], default='RUNNING', max_length=20),
        ),
    ]
