# Generated by Django 5.2.14 on 2026-05-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_run_attempt_run_run_data_alter_run_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapersettings',
            name='max_execution_attempts',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('FINISHED', 'Finished'), ('PAUSED', 'Paused'), ('FAILED', 'Failed')], default='QUEUED', max_length=20),
        ),
    ]
