# Generated by Django 5.2.14 on 2026-05-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_scrapersettings_max_execution_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='run_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
