# Generated by Django 6.0.6 on 2026-06-14 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_run_run_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='batch',
            field=models.IntegerField(default=0),
        ),
    ]
